const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url)).replace(/\/$/,'');
const server=createServer(async(req,res)=>{try{const path=req.url==='/'?'/index.html':req.url;const data=await readFile(root+path);res.setHeader('Content-Type',path.endsWith('.html')?'text/html':path.endsWith('.js')?'application/javascript':path.endsWith('.json')?'application/json':'image/png');res.end(data);}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;
try{
 browser=await chromium.launch({headless:true});
 const schedules=[];
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/push/devices/**',async route=>{if(route.request().method()==='PUT')schedules.push(route.request().postDataJSON());await route.fulfill({status:200,contentType:'application/json',body:'{"ok":true}'});});
 await page.goto('http://127.0.0.1:'+server.address().port);
 await page.getByRole('button',{name:'9er',exact:true}).click();
 await page.locator('#opt-period-0').fill('17.5');
 await page.locator('#opt-period-0').press('Tab');
 await page.locator('#opt-period-1').fill('23');await page.locator('#opt-period-1').press('Tab');
 await page.locator('#opt-breakMin').fill('0');await page.locator('#opt-breakMin').press('Tab');
 await page.screenshot({path:'/private/tmp/bytte-settings.png',fullPage:true});
 await page.getByRole('button',{name:'Velg spillere →'}).click();
 for(let i=1;i<=11;i++){await page.locator('#newname').fill('Spiller '+i);await page.locator('#newname').press('Enter');}
 await page.getByRole('button',{name:'Spiller 1',exact:true}).nth(1).click();
 await page.getByRole('button',{name:'Se oppstilling →'}).click();
 assert.equal(await page.locator('.pcard').count(),11);
 await page.getByRole('button',{name:'Test lyd',exact:true}).click();
 assert.match(await page.locator('#alert-settings').innerText(),/Hørte du to pip/);
 await page.evaluate(()=>{alertPrefs().notifications=true;db.pushDevice={id:'test-device',token:'test-token',revision:0};save();});
 await page.waitForFunction(()=>pushState==='ready');
 assert.deepEqual(schedules.at(-1).events,[]);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'/private/tmp/bytte-lineup.png',fullPage:true});
 await page.getByRole('button',{name:'Se bytteplan',exact:true}).click();await page.getByRole('button',{name:'Lukk',exact:true}).click();
 await page.getByRole('button',{name:'Start klokka og kampen ▶'}).click();
 assert.match(await page.locator('#clock').innerText(),/17:30/);
 await page.waitForFunction(()=>pushState==='ready');assert.equal(schedules.at(-1).events.length,3);
 await page.getByRole('button',{name:'⏸ Pause',exact:true}).click();await page.waitForFunction(()=>pushState==='ready');assert.deepEqual(schedules.at(-1).events,[]);
 await page.getByRole('button',{name:'▶ Start',exact:true}).click();await page.waitForFunction(()=>pushState==='ready');assert.equal(schedules.at(-1).events.length,3);
 await page.screenshot({path:'/private/tmp/bytte-live.png',fullPage:true});
 await page.reload();assert.match(await page.locator('#clock').innerText(),/17:30/);
 await page.evaluate(()=>{db.match.lastTickAt=Date.now()-2000000;tick();});
 await page.getByRole('button',{name:'Start periode 2 ▶'}).click();assert.match(await page.locator('#clock').innerText(),/23:00/);
 await page.getByRole('button',{name:'Avslutt',exact:true}).click();await page.getByRole('button',{name:'Lagre statistikk og avslutt'}).click();
 await page.getByRole('button',{name:'Lukk',exact:true}).click();
 await page.waitForFunction(()=>pushState==='ready');assert.deepEqual(schedules.at(-1).events,[]);
 assert.deepEqual(errors,[]);
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;await caches.open('unrelated-cache');});
 await page.reload();
 await page.context().setOffline(true);await page.reload();assert.match(await page.title(),/Bytteplan/);
 await page.context().setOffline(false);
 assert.equal(await page.evaluate(async()=> (await caches.keys()).includes('unrelated-cache')),true);
 await page.getByRole('button',{name:'⚽ Kamp',exact:true}).click();
 await page.getByRole('button',{name:'3er',exact:true}).click();
 await page.locator('#opt-period-0').fill('11');
 await page.getByRole('button',{name:'Velg spillere →'}).click();
 assert.equal(await page.locator('#newname').count(),1,'Next works directly after editing a number');
 assert.deepEqual(errors,[]);
 console.log('Sound-test UI and push schedule sync on start, pause, resume and end passed (mock transport).');
 console.log('Offline reload, cache isolation and direct next-button input flow passed.');
 console.log('Mobile browser flow, custom times, 9er, preview, reload, period transitions and history passed.');
}finally{await browser?.close();server.close();}
